### PR TITLE
Updated currencies

### PR DESCRIPTION
**Pull request by gmponos**

### CODE REVIEW

**Comment by frederikbosch** [comment]
This cannot be accepted. We use this https://github.com/moneyphp/iso-currencies package as source for currencies, which in turn uses some official source. If you want to update iso currencies, update via that package.

**Comment by gmponos** [comment]
Most probably I should have written that in the description but what I did was run the composer command that you have in the current package and commit the changes.

**Comment by gmponos** [comment]
I am talking about [this command](https://github.com/moneyphp/money/blob/master/composer.json#L67) which uses the iso-currencies package.

**Comment by frederikbosch** [comment]
Ah, then it is completely reasonable. I will check after weekend and merge it then.

**Pull request merged**
