### PR TITLE
Improve tests of parsers

### PR DESCRIPTION
**Pull request by gmponos**
before merging #529 if we could merge this first..

### CODE REVIEW

**Comment by gmponos** [comment]
In short description:

-  Added more cases to `IntlLocalizedDecimalParserTest`
https://github.com/moneyphp/money/pull/586/files#diff-380f41fd51dd5f28ab63197ddc29fe85R116
- Replaces with equals https://github.com/moneyphp/money/pull/586/files#diff-380f41fd51dd5f28ab63197ddc29fe85R57
- Use actual Currency object instead of a Prophecy one: https://github.com/moneyphp/money/pull/586/files#diff-380f41fd51dd5f28ab63197ddc29fe85R23

**Comment by sagikazarmark** [comment]
Why replace mocks with actual implementations?

**Comment by gmponos** [comment]
> Why replace mocks with actual implementations?

For the usual reasons.. hahaah

- I have seen cases in the past where there were many WTF moments because of mocks... For instance say that it throws an exception although it never does.. for the sake of good programming practices I switched here to actual implementation.
- Although speed is not a problem here.. `Prophesize` is way heavier.

Let's not make a big deal out of it.. if this is no good I will revert.. no problem.

**Comment by sagikazarmark** [comment]
Even if we consider replacing mocks with actual implementations, that should be a separate PR, probably covering the whole library.

**Comment by gmponos** [comment]
Revert the test changes :)

**Review by sagikazarmark — APPROVED** [review]
Thanks!

**Pull request merged**
