### PR TITLE
Fix floating point casting to integer in PHP calculator

### LINKED ISSUE #455: Float to string casting provides errors on some locales
```php
$full_summ = new Money(1000000, new Currency('RUB'));
$vat_summ = $full_summ->divide(1.18);

echo 'Should be: ' . round(10000/1.18, 2);
echo "<br>\n";
echo 'We have: '. $vat_summ->getAmount()/100;
```

Gives us:
```
Should be: 8474,58
We have: 8474,57
```

After debugging I found that it's because of `divide($amount, $divisor)` in `PhpCalculator.php` — there we have `return (string) $result` — on some locales (e.g. ru_RU.UTF8) it creates 847457,627 instead of 847457.627 and after that that part after the comma are gone in further operations.

### PR DESCRIPTION
**Pull request by sagikazarmark**
Fixes #455

### CODE REVIEW

**Comment by sagikazarmark** [comment]
@chekalskiy can you please check if this solves the issue for you?

**Comment by sagikazarmark** [comment]
Yup, it did.

**Comment by chekalskiy** [comment]
I'll check a bit later. Thank you

**Comment by chekalskiy** [comment]
I've tested and now my test case looks fine. 👍

But shouldn't we add `castString()` to `add()`, `subtract()`, `absolute()` and `mod()` methods?

**Comment by sagikazarmark** [comment]
No, as they don't involve casting float to string:

- add: adding two integers will result in an integer anyway
- subtract: subtracting one integer from another will result in an integer
- absolute: there is no calculation related to precision
- mod: there is no calculation related to precision

**Comment by sagikazarmark** [comment]
But I've just found other places where the tests break. I added a new test case for running all tests with russian UTF8 locale for the php calculator.

**Comment by sagikazarmark** [comment]
@frederikbosch see the separate commit with the breaking tests. Solution pushed in a separate commit.

**Comment by sagikazarmark** [comment]
Merging this as it fixes the problem, but I'm going to do some refactoring around the number class. I feel that there is too many string casting here and there.

**Comment by frederikbosch** [comment]
Totally agree. In my perception, in version 4 we should use Number everwhere internally. That means only accepting Number or directly do the conversion on every numeric parameter.

**Pull request merged**
