### PR TITLE
Remove setUp template method

### PR DESCRIPTION
**Pull request by samnela**

### CODE REVIEW

**Comment by frederikbosch** [comment]
Thanks

**Comment by gmponos** [comment]
Just out of curiosity.. is there any benefit by removing it other than getting rid of the extra function call?

**Comment by frederikbosch** [comment]
Not that I am aware of. Usually I have the following standard for libraries with high code coverage: any code that can be removed and still passes tests, should be removed.

**Comment by sagikazarmark** [comment]
I guess it can also be a readability thing: don't have to check what the parent does, because it does nothing.

**Pull request merged**
