### PR TITLE
gmp: fix multiplier with leading zero

### LINKED ISSUE #286: GmpCalculator multiply:  gmp_init() error when fractional part with leading 0
```PHP
$phpCalculator = new \Money\Calculator\PhpCalculator;
$gmpCalculator = new \Money\Calculator\GmpCalculator;
$bcCalculator = new \Money\Calculator\BcMathCalculator;
echo $phpCalculator->multiply('100', 0.029) . "\n"; // 2.9
echo $gmpCalculator->multiply('100', 0.029) . "\n"; // .0 gmp_init(): Unable to convert variable to GMP - string is not an integer
echo $bcCalculator->multiply('100', 0.029) . "\n"; // 2.900
```

### PR DESCRIPTION
**Pull request by frederikbosch**
Fixes #286

### CODE REVIEW

**Comment by sagikazarmark** [comment]
So is it actually something which can be fixed? Not a limitation of GMP, like in the referenced issue?

**Comment by frederikbosch** [comment]
@sagikazarmark In the case of issue #278, there was an example that could never be the case inside `Money`. Why would you want to compare non-integers? That is simply impossible with Money because Money requires the amount to be integer. We never compare non-integers.

But issue #286 is different. One should be able to multiply an amount with decimal leading zero value. As you can see in the multiply method I created a workaround the limitation of `GMP`.

My point with the calculators is: they are Money internals. Anything inside the calculators that causes bugs inside Money should be fixed. Every other case should be ignored.

**Comment by frederikbosch** [comment]
@sagikazarmark Decimals within `Money` are only relevant when multiplying or with divisions. That is why I only created the workaround inside the GMP calculator for `multiply` and `divide`. Decimals are irrelevant when adding, subtracting and comparing because `Money` will always require integers for those methods.

**Comment by sagikazarmark** [comment]
@frederikbosch okay, agreed.

**Pull request merged**
