### PR TITLE
Update bitcoin.rst

### PR DESCRIPTION
**Pull request by gerardroche**
BitcoinMoneyParser accepts only number of fraction digits: `BitcoinMoneyParser::__construct($fractionDigits)`

### CODE REVIEW

**Comment by frederikbosch** [comment]
@sagikazarmark Continue supporting hhvm and update travis? Or drop? Maybe drop next major version.

**Comment by sagikazarmark** [comment]
HHVM support was never my top priority. As a fellow PHP developer expressed what HHVM was good for:

> hhvm seems to have done its job by pushing the php core devs to make php 7 about as fast as hhvm

**Comment by frederikbosch** [comment]
Totally agree. Drop on Travis now then? Or wait for 4.x?

**Comment by frederikbosch** [comment]
It fails due to misconfiguration (something on ubuntu version). We should update the travis.yml. Adding it to allowed_failures would be the same as removing it. Because we are not testing hhvm now/then.

**Comment by frederikbosch** [comment]
So we have three options.

1. Make sure HHVM tests work, but are allowed to fail
2. Make sure HHVM tests work, but are not allowed to fail
3. Drop HHVM tests

My preference is number three.

**Comment by sagikazarmark** [comment]
I would say as a quick fix we should just allow it to fail then invest some time and check if we can fix the tests and properly support HHVM. If we can do that with a reasonable effort then we should, if not we can drop it entirely. I don't recall exactly what HHVM specific code we have, so I can't make a commitment to drop it right now.

**Comment by frederikbosch** [comment]
Bueno

**Comment by frederikbosch** [comment]
Thanks!

**Pull request merged**
