### PR TITLE
[FEATURE] typehints for static methods

### PR DESCRIPTION
**Pull request by Gummibeer**
related to #409 - this is my console command to create a helper file with all the static methods.

## How to

1) call from composer - generates the file in the package root folder:
```bash
composer generate-ide-helper
```

2) call from composer binary (`vendor/bin/money-console`):
```bash
vendor/bin/money-console generate:money-static:helper

--path=[path|package root] - define a custom path to store the helper file
--indent=[int|4] - define the amount of spaces to use for indent
--currencies=[full classname] - the classname to a custom currencies class. can be used multiple times

vendor/bin/money-console generate:money-static:helper --path=./ --indent=2 --currencies=App\Currencies\Class1 --currencies=App\Currencies\Class2
```

The output is very verbose and I think catches all exceptions in a good way.

> $ ./money-console generate:money-static:helper
> Generate Money\Money static method helper class
> Target-File:
> [...]/money/_ide_helper.money.php
> Currencies-Classes:
> Money\Currencies\ISOCurrencies
> Money\Currencies\BitcoinCurrencies
> Found-Currencies:
> 179
> helper class successfully written

The generated file is ignored at the moment because otherwise the package will everytime come with an `Other decleration of class Money exists` warning in the IDE. I can remove the file from the ignore list if wanted - but I think that this isn't a good idea.
If you want to have this file in the repo it would be an idea to use travis and push the file with markup into the `doc` folder. For this I can add a second command that generates the `.rst` file.

### CODE REVIEW

**Comment by Gummibeer** [comment]
This is the generated file including both default currencies classes (`ISOCurrencies`, `BitcoinCurrencies`).

**_ide_helper.money.php**
```php
<?php
namespace Money;

class Money
{
    public static function AFN($amount) {
        return new self($amount, new Currency('AFN'));
    }

    public static function EUR($amount) {
        return new self($amount, new Currency('EUR'));
    }

    public static function ALL($amount) {
        return new self($amount, new Currency('ALL'));
    }

    public static function DZD($amount) {
        return new self($amount, new Currency('DZD'));
    }

    public static function USD($amount) {
        return new self($amount, new Currency('USD'));
    }

    public static function AOA($amount) {
        return new self($amount, new Currency('AOA'));
    }

    public static function XCD($amount) {
        return new self($amount, new Currency('XCD'));
    }

    public static function ARS($amount) {
        return new self($amount, new Currency('ARS'));
    }

    public static function AMD($amount) {
        return new self($amount, new Currency('AMD'));
    }

    public static function AWG($amount) {
        return new self($amount, new Currency('AWG'));
    }

    public static function AUD($amount) {
        return new self($amount, new Currency('AUD'));
    }

    public static function AZN($amount) {
        return new self($amount, new Currency('AZN'));
    }

    public static function BSD($amount) {
        return new self($amount, new Currency('BSD'));
    }

    public static function BHD($amount) {
        return new self($amount, new Currency('BHD'));
    }

    public static function BDT($amount) {
        return new self($amount, new Currency('BDT'));
    }

    public static function BBD($amount) {
        return new self($amount, new Currency('BBD'));
    }

    public static function BYN($amount) {
        return new self($amount, new Currency('BYN'));
    }

    public static function BZD($amount) {
        return new self($amount, new Currency('BZD'));
    }

    public static function XOF($amount) {
        return new self($amount, new Currency('XOF'));
    }

    public static function BMD($amount) {
        return new self($amount, new Currency('BMD'));
    }

    public static function INR($amount) {
        return new self($amount, new Currency('INR'));
    }

    public static function BTN($amount) {
        return new self($amount, new Currency('BTN'));
    }

    public static function BOB($amount) {
        return new self($amount, new Currency('BOB'));
    }

    public static function BOV($amount) {
        return new self($amount, new Currency('BOV'));
    }

    public static function BAM($amount) {
        return new self($amount, new Currency('BAM'));
    }

    public static function BWP($amount) {
        return new self($amount, new Currency('BWP'));
    }

    public static function NOK($amount) {
        return new self($amount, new Currency('NOK'));
    }

    public static function BRL($amount) {
        return new self($amount, new Currency('BRL'));
    }

    public static function BND($amount) {
        return new self($amount, new Currency('BND'));
    }

    public static function BGN($amount) {
        return new self($amount, new Currency('BGN'));
    }

    public static function BIF($amount) {
        return new self($amount, new Currency('BIF'));
    }

    public static function CVE($amount) {
        return new self($amount, new Currency('CVE'));
    }

    public static function KHR($amount) {
        return new self($amount, new Currency('KHR'));
    }

    public static function XAF($amount) {
        return new self($amount, new Currency('XAF'));
    }

    public static function CAD($amount) {
        return new self($amount, new Currency('CAD'));
    }

    public static function KYD($amount) {
        return new self($amount, new Currency('KYD'));
    }

    public static function CLP($amount) {
        return new self($amount, new Currency('CLP'));
    }

    public static function CLF($amount) {
        return new self($amount, new Currency('CLF'));
    }

    public static function CNY($amount) {
        return new self($amount, new Currency('CNY'));
    }

    public static function COP($amount) {
        return new self($amount, new Currency('COP'));
    }

    public static function COU($amount) {
        return new self($amount, new Currency('COU'));
    }

    public static function KMF($amount) {
        return new self($amount, new Currency('KMF'));
    }

    public static function CDF($amount) {
        return new self($amount, new Currency('CDF'));
    }

    public static function NZD($amount) {
        return new self($amount, new Currency('NZD'));
    }

    public static function CRC($amount) {
        return new self($amount, new Currency('CRC'));
    }

    public static function HRK($amount) {
        return new self($amount, new Currency('HRK'));
    }

    public static function CUP($amount) {
        return new self($amount, new Currency('CUP'));
    }

    public static function CUC($amount) {
        return new self($amount, new Currency('CUC'));
    }

    public static function ANG($amount) {
        return new self($amount, new Currency('ANG'));
    }

    public static function CZK($amount) {
        return new self($amount, new Currency('CZK'));
    }

    public static function DKK($amount) {
        return new self($amount, new Currency('DKK'));
    }

    public static function DJF($amount) {
        return new self($amount, new Currency('DJF'));
    }

    public static function DOP($amount) {
        return new self($amount, new Currency('DOP'));
    }

    public static function EGP($amount) {
        return new self($amount, new Currency('EGP'));
    }

    public static function SVC($amount) {
        return new self($amount, new Currency('SVC'));
    }

    public static function ERN($amount) {
        return new self($amount, new Currency('ERN'));
    }

    public static function ETB($amount) {
        return new self($amount, new Currency('ETB'));
    }

    public static function FKP($amount) {
        return new self($amount, new Currency('FKP'));
    }

    public static function FJD($amount) {
        return new self($amount, new Currency('FJD'));
    }

    public static function XPF($amount) {
        return new self($amount, new Currency('XPF'));
    }

    public static function GMD($amount) {
        return new self($amount, new Currency('GMD'));
    }

    public static function GEL($amount) {
        return new self($amount, new Currency('GEL'));
    }

    public static function GHS($amount) {
        return new self($amount, new Currency('GHS'));
    }

    public static function GIP($amount) {
        return new self($amount, new Currency('GIP'));
    }

    public static function GTQ($amount) {
        return new self($amount, new Currency('GTQ'));
    }

    public static function GBP($amount) {
        return new self($amount, new Currency('GBP'));
    }

    public static function GNF($amount) {
        return new self($amount, new Currency('GNF'));
    }

    public static function GYD($amount) {
        return new self($amount, new Currency('GYD'));
    }

    public static function HTG($amount) {
        return new self($amount, new Currency('HTG'));
    }

    public static function HNL($amount) {
        return new self($amount, new Currency('HNL'));
    }

    public static function HKD($amount) {
        return new self($amount, new Currency('HKD'));
    }

    public static function HUF($amount) {
        return new self($amount, new Currency('HUF'));
    }

    public static function ISK($amount) {
        return new self($amount, new Currency('ISK'));
    }

    public static function IDR($amount) {
        return new self($amount, new Currency('IDR'));
    }

    public static function XDR($amount) {
        return new self($amount, new Currency('XDR'));
    }

    public static function IRR($amount) {
        return new self($amount, new Currency('IRR'));
    }

    public static function IQD($amount) {
        return new self($amount, new Currency('IQD'));
    }

    public static function ILS($amount) {
        return new self($amount, new Currency('ILS'));
    }

    public static function JMD($amount) {
        return new self($amount, new Currency('JMD'));
    }

    public static function JPY($amount) {
        return new self($amount, new Currency('JPY'));
    }

    public static function JOD($amount) {
        return new self($amount, new Currency('JOD'));
    }

    public static function KZT($amount) {
        return new self($amount, new Currency('KZT'));
    }

    public static function KES($amount) {
        return new self($amount, new Currency('KES'));
    }

    public static function KPW($amount) {
        return new self($amount, new Currency('KPW'));
    }

    public static function KRW($amount) {
        return new self($amount, new Currency('KRW'));
    }

    public static function KWD($amount) {
        return new self($amount, new Currency('KWD'));
    }

    public static function KGS($amount) {
        return new self($amount, new Currency('KGS'));
    }

    public static function LAK($amount) {
        return new self($amount, new Currency('LAK'));
    }

    public static function LBP($amount) {
        return new self($amount, new Currency('LBP'));
    }

    public static function LSL($amount) {
        return new self($amount, new Currency('LSL'));
    }

    public static function ZAR($amount) {
        return new self($amount, new Currency('ZAR'));
    }

    public static function LRD($amount) {
        return new self($amount, new Currency('LRD'));
    }

    public static function LYD($amount) {
        return new self($amount, new Currency('LYD'));
    }

    public static function CHF($amount) {
        return new self($amount, new Currency('CHF'));
    }

    public static function MOP($amount) {
        return new self($amount, new Currency('MOP'));
    }

    public static function MKD($amount) {
        return new self($amount, new Currency('MKD'));
    }

    public static function MGA($amount) {
        return new self($amount, new Currency('MGA'));
    }

    public static function MWK($amount) {
        return new self($amount, new Currency('MWK'));
    }

    public static function MYR($amount) {
        return new self($amount, new Currency('MYR'));
    }

    public static function MVR($amount) {
        return new self($amount, new Currency('MVR'));
    }

    public static function MRO($amount) {
        return new self($amount, new Currency('MRO'));
    }

    public static function MUR($amount) {
        return new self($amount, new Currency('MUR'));
    }

    public static function XUA($amount) {
        return new self($amount, new Currency('XUA'));
    }

    public static function MXN($amount) {
        return new self($amount, new Currency('MXN'));
    }

    public static function MXV($amount) {
        return new self($amount, new Currency('MXV'));
    }

    public static function MDL($amount) {
        return new self($amount, new Currency('MDL'));
    }

    public static function MNT($amount) {
        return new self($amount, new Currency('MNT'));
    }

    public static function MAD($amount) {
        return new self($amount, new Currency('MAD'));
    }

    public static function MZN($amount) {
        return new self($amount, new Currency('MZN'));
    }

    public static function MMK($amount) {
        return new self($amount, new Currency('MMK'));
    }

    public static function NAD($amount) {
        return new self($amount, new Currency('NAD'));
    }

    public static function NPR($amount) {
        return new self($amount, new Currency('NPR'));
    }

    public static function NIO($amount) {
        return new self($amount, new Currency('NIO'));
    }

    public static function NGN($amount) {
        return new self($amount, new Currency('NGN'));
    }

    public static function OMR($amount) {
        return new self($amount, new Currency('OMR'));
    }

    public static function PKR($amount) {
        return new self($amount, new Currency('PKR'));
    }

    public static function PAB($amount) {
        return new self($amount, new Currency('PAB'));
    }

    public static function PGK($amount) {
        return new self($amount, new Currency('PGK'));
    }

    public static function PYG($amount) {
        return new self($amount, new Currency('PYG'));
    }

    public static function PEN($amount) {
        return new self($amount, new Currency('PEN'));
    }

    public static function PHP($amount) {
        return new self($amount, new Currency('PHP'));
    }

    public static function PLN($amount) {
        return new self($amount, new Currency('PLN'));
    }

    public static function QAR($amount) {
        return new self($amount, new Currency('QAR'));
    }

    public static function RON($amount) {
        return new self($amount, new Currency('RON'));
    }

    public static function RUB($amount) {
        return new self($amount, new Currency('RUB'));
    }

    public static function RWF($amount) {
        return new self($amount, new Currency('RWF'));
    }

    public static function SHP($amount) {
        return new self($amount, new Currency('SHP'));
    }

    public static function WST($amount) {
        return new self($amount, new Currency('WST'));
    }

    public static function STD($amount) {
        return new self($amount, new Currency('STD'));
    }

    public static function SAR($amount) {
        return new self($amount, new Currency('SAR'));
    }

    public static function RSD($amount) {
        return new self($amount, new Currency('RSD'));
    }

    public static function SCR($amount) {
        return new self($amount, new Currency('SCR'));
    }

    public static function SLL($amount) {
        return new self($amount, new Currency('SLL'));
    }

    public static function SGD($amount) {
        return new self($amount, new Currency('SGD'));
    }

    public static function XSU($amount) {
        return new self($amount, new Currency('XSU'));
    }

    public static function SBD($amount) {
        return new self($amount, new Currency('SBD'));
    }

    public static function SOS($amount) {
        return new self($amount, new Currency('SOS'));
    }

    public static function SSP($amount) {
        return new self($amount, new Currency('SSP'));
    }

    public static function LKR($amount) {
        return new self($amount, new Currency('LKR'));
    }

    public static function SDG($amount) {
        return new self($amount, new Currency('SDG'));
    }

    public static function SRD($amount) {
        return new self($amount, new Currency('SRD'));
    }

    public static function SZL($amount) {
        return new self($amount, new Currency('SZL'));
    }

    public static function SEK($amount) {
        return new self($amount, new Currency('SEK'));
    }

    public static function CHE($amount) {
        return new self($amount, new Currency('CHE'));
    }

    public static function CHW($amount) {
        return new self($amount, new Currency('CHW'));
    }

    public static function SYP($amount) {
        return new self($amount, new Currency('SYP'));
    }

    public static function TWD($amount) {
        return new self($amount, new Currency('TWD'));
    }

    public static function TJS($amount) {
        return new self($amount, new Currency('TJS'));
    }

    public static function TZS($amount) {
        return new self($amount, new Currency('TZS'));
    }

    public static function THB($amount) {
        return new self($amount, new Currency('THB'));
    }

    public static function TOP($amount) {
        return new self($amount, new Currency('TOP'));
    }

    public static function TTD($amount) {
        return new self($amount, new Currency('TTD'));
    }

    public static function TND($amount) {
        return new self($amount, new Currency('TND'));
    }

    public static function TRY($amount) {
        return new self($amount, new Currency('TRY'));
    }

    public static function TMT($amount) {
        return new self($amount, new Currency('TMT'));
    }

    public static function UGX($amount) {
        return new self($amount, new Currency('UGX'));
    }

    public static function UAH($amount) {
        return new self($amount, new Currency('UAH'));
    }

    public static function AED($amount) {
        return new self($amount, new Currency('AED'));
    }

    public static function USN($amount) {
        return new self($amount, new Currency('USN'));
    }

    public static function UYU($amount) {
        return new self($amount, new Currency('UYU'));
    }

    public static function UYI($amount) {
        return new self($amount, new Currency('UYI'));
    }

    public static function UZS($amount) {
        return new self($amount, new Currency('UZS'));
    }

    public static function VUV($amount) {
        return new self($amount, new Currency('VUV'));
    }

    public static function VEF($amount) {
        return new self($amount, new Currency('VEF'));
    }

    public static function VND($amount) {
        return new self($amount, new Currency('VND'));
    }

    public static function YER($amount) {
        return new self($amount, new Currency('YER'));
    }

    public static function ZMW($amount) {
        return new self($amount, new Currency('ZMW'));
    }

    public static function ZWL($amount) {
        return new self($amount, new Currency('ZWL'));
    }

    public static function XBA($amount) {
        return new self($amount, new Currency('XBA'));
    }

    public static function XBB($amount) {
        return new self($amount, new Currency('XBB'));
    }

    public static function XBC($amount) {
        return new self($amount, new Currency('XBC'));
    }

    public static function XBD($amount) {
        return new self($amount, new Currency('XBD'));
    }

    public static function XTS($amount) {
        return new self($amount, new Currency('XTS'));
    }

    public static function XXX($amount) {
        return new self($amount, new Currency('XXX'));
    }

    public static function XAU($amount) {
        return new self($amount, new Currency('XAU'));
    }

    public static function XPD($amount) {
        return new self($amount, new Currency('XPD'));
    }

    public static function XPT($amount) {
        return new self($amount, new Currency('XPT'));
    }

    public static function XAG($amount) {
        return new self($amount, new Currency('XAG'));
    }

    public static function XBT($amount) {
        return new self($amount, new Currency('XBT'));
    }
}
```

**Comment by Gummibeer** [comment]
@sagikazarmark have you changed the styleci settings? I haven't changed these files and there are also no changes in master branch.
Should I ignore them or create a new PR to fix these issues?

**Comment by frederikbosch** [comment]
@sagikazarmark Do you get what is happening here? Can you make sure this will be merged?

**Comment by sagikazarmark** [comment]
Haven't had the chance to try it, but I like the idea of having a generated something that causes the IDE to show proper typehints. IMO it's much more than adding them to Money.

This script generates a file which is not autoloaded, but read by IDEs, so they can properly show typehints for magic ISO currency constructors.

As said I haven't reviewed it properly, but I would say it's not a blocker, so if we can't make it into 3.1, that's not a huge problem. I will try to pick it up this week.

**Comment by Gummibeer** [comment]
It generated a helper php file for all passed in "Currencies" classes. This helper file does not have any effect on runtime cause it's not autoloaded. But most (every?) IDEs read all php files in project directory - that's why it also detects this helper file and can display all static methods listed in it for autocomplete.
The user/dev just has to execute the command (see first comment) and has this file, if wanted or available also with all custom Currencies.

It is the solution for the, wanted, PHP Doc Tags in the Money class itself.

**Comment by frederikbosch** [comment]
@willemstuursma As you mentioned yesterday that you would like to see this land, could you reply and say if this is what you are looking for?

**Comment by willemstuursma** [comment]
> @willemstuursma As you mentioned yesterday that you would like to see this land, could you reply and say if this is what you are looking for?

To be quite frank, I would prefer all out of the box supported currencies (ISO + XBT) to be configured as magic methods in the phpdoc for the `Money` class. 

I a library consumer, I don't really spend any time in the `Money` class and as a `Money` developer, I can always collapse the comments using my IDE. 

Having a helper script is better than nothing, but not the _best_ solution for library consumers.

**Comment by willemstuursma** [comment]
What if we were to move the phpdoc with the method definitions into a trait or interface that is used exclusively for this?

**Comment by Gummibeer** [comment]
@willemstuursma so you want something like:

**repo code**
```php
class Money {
    use MoneyStaticHelperDoc;
}

trait MoneyStaticHelperDoc {}
```

**CI/local Command override**
```php
/**
 * @method ...
 */
trait MoneyStaticHelperDoc {}
```

Cause of the fact that this is already here I would be fine to extend this and add a second symfony command. So every user/dev can use his favorite way.
If I got your idea right I will test if it works in PhpStorm and if it does I will create a second command.

**Comment by willemstuursma** [comment]
@Gummibeer I'd prefer an auto generated file that is part of the repository - so no set up needed, and scripts only needed for re-generating the file if new currencies are added. 

I'd also move the `__callStatic()` method into the trait, so I'd name it something like `Money\Money\StaticHelperMethodsTrait`.

**Comment by Gummibeer** [comment]
Ok, but if it is autogenerated you have to commit/Push it from TravisCI or anyone who Changes something related has to generate it!?
But in all cases we need a second command.

**Comment by frederikbosch** [comment]
Since there is no consensus yet in this PR, I will release 3.1 without it.

**Comment by Gummibeer** [comment]
@willemstuursma & @frederikbosch I've added the requested trait solution. And merged the latest master.

**Comment by frederikbosch** [comment]
I think it's a really bad idea to add a trait to `Money` for the sake of code completion.

**Comment by Gummibeer** [comment]
@frederikbosch I also, but it was the wish by @willemstuursma. The IDE helper file works pretty good and does what was requested.

**Comment by sagikazarmark** [comment]
@frederikbosch I think it's an acceptable compromise in this case. It's ugly for sure, but let's think of it this way: if there wasn't `__callStatic` (which is - let's be honest - also not really nice) you would have to generate all that code.

In fact, I think we could even move that callStatic function to the generated trait as well. That way all ISO static nastiness is moved out of money (on the implementation level). But that's just an idea.

I did a little research and without writing an actual idea plugin (which just blows a mind) we probably can't achieve dynamic methods without this. Unfortunately this are is barely covered by JetBrains and Google.

**Comment by sagikazarmark** [comment]
☝️  I created a separate PR with my experiments based on your code @Gummibeer . Any input is welcome there.

**Pull request closed without merging**
