### PR TITLE
Make TOC & content improvements to documentation

### PR DESCRIPTION
**Pull request by tuwannu**
Reading the file diffs here will be difficult. So I created a RTD build to see the actual rendered docs from this PR here: http://tuwannu-money.readthedocs.io/

I made quite a few significant changes, so I'm not expecting this PR to be accepted on my first submission. Any suggestions are welcomed!

### CODE REVIEW

**Comment by sagikazarmark** [comment]
@tuwannu first of all, thank you very much for your PR, I appreciate it.

Secondly: without a review I already see that this will conflict with #308. May I suggest that we wait for that to be merged without proceeding this one?

**Comment by tuwannu** [comment]
Ah, my bad for not realizing there is a `doc` branch.

I'll wait for #308 to be merged, then I will re-evaluate my PR.

**Comment by sagikazarmark** [comment]
Thank you very much @tuwannu

**Comment by sagikazarmark** [comment]
Alright, I merged #308, can you please rebase?

**Comment by tuwannu** [comment]
Heavy conflicts so I decided to make a new PR #312 instead.

**Pull request closed without merging**
