### PR TITLE
numeric-string DecimalMoneyFormatter return type

### PR DESCRIPTION
**Pull request by rogervila**
`DecimalMoneyFormatter` format method returns always a `numeric-string` value.

### CODE REVIEW

**Comment by rogervila** [comment]
Well, It needs additional Psalm config. @frederikbosch before going on with this PR, do you agree with the change?

**Comment by frederikbosch** [comment]
I think the new docblock is correct indeed, decimal formatter returns a numeric-string.

**Comment by frederikbosch** [comment]
I am not a Pslam guru, but if that error is fixed, I can merge this.

**Comment by rogervila** [comment]
Thank you @frederikbosch, I have fixed the PR, let me know if there is any additional change needed.

**Pull request merged**
