### PR TITLE
Bitcoin namespace and currencies

### LINKED ISSUE #197: Bitcoin supported parser/formatter
Do we need the supported word? Simply BitcoinMoneyParser/Formatter?

I don't think we are forced to put every nature/capability of the class in the name.

### PR DESCRIPTION
**Pull request by frederikbosch**
Move bitcoin to own namespace, rename classes, add currencies implementation. Fixed #197.

### CODE REVIEW

**Comment by frederikbosch** [comment]
@sagikazarmark Can you have a look? I realized we were missing the Currencies implementation for Bitcoin so I added that one too. With a third Bitcoin class I decided to move it to a separate namespace. This can be argued.

**Comment by sagikazarmark** [comment]
I will take a look at it.

First thought: I would rather create an aggregate currency repository instead of using decorator here.

**Comment by frederikbosch** [comment]
@sagikazarmark The Currencies implementation for Bitcoin does not withhold us from creating an aggregate repository. Creating a repo is a good idea. It could be added in version 3.1. In this cade a decorator is the quickest way to complete support for bitcoin. And it does not harm anyone.

**Comment by sagikazarmark** [comment]
> And it does not harm anyone.

No, it does not, but is not-so-good design IMO. It would encourage people to create decorators like this.

Decorators perform well when a specific behaviour needs to be added to very well defined interfaces, which is not really true for a repository.

I was thinking about something like this:

``` php
final class AggregateCurrencies implements Currencies
{
    private $currencies;

    public function __construct($currencies)
    {
        $this->currencies = $currency;
    }

    public function contains(Currency $currency)
    {
        foreach ($this->currencies as $currencies) {
            if ($currencies->contains($currency)) {
                return true;
            }
        }

        return false;
    }
}
```

This way bitcoin currency repository would only be responsible for bitcoin.

It is also easier to configure in DI (while configuring long decorator-chains can be hard or confusing)

**Comment by frederikbosch** [comment]
@sagikazarmatk Agreed. Let's do the aggregate repo. Maybe close this one then, and reissue this PR with only formatter and parser classes renamed.

What do you think BitcoinMoneyFormatter or BitcoinFormatter. My vote goes to the latter but wonder what you think.

**Comment by sagikazarmark** [comment]
> Maybe close this one then

Not necessary to close. Mark it [WIP] and then rebase when aggregate is added separately.

AFAIK it was your argument to call them MoneyFormatters, because we might want to add other formatters?

What's important for me is to have consistent naming and structure. Here are the options I could imagine:

- Have them in Bitcoin namespace and call them simply MoneyFormatter and MoneyParser.
- Have them in their respective namespace (Formatter, Parser) and call them BitcoinMoneyFormatter and BitcoinMoneyParser
- Call them BitcoinFormatter/Parser, but we should have similar naming in case of other parsers/formatters? (IntlFormatter?)

(BTW consistency and structure: should we have a Currencies namespace? If we put BitcoinCurrencies in Currencies namespace with ISO it would make sense IMO)

**Comment by frederikbosch** [comment]
Ok. I'll update this PR next week.

- No more Bitcoin namespace.
- Class names will be BitcoinMoneyFormatter and BitcoinMoneyParser in the namespaces Formatter and Parser.
- BitcoinCurrencies will be dropped.
- Currencies namespace will be added and will contain ISOCurrencies and AggregateCurrencies.

Ok?

**Comment by sagikazarmark** [comment]
> BitcoinCurrencies will be dropped

I didn't say `BitcoinCurrencies` should be dropped :wink: 

It should be there, but only contain bitcoin. Also, maybe constants from Formatter and Parser might be moved here as the source of all truth.

**Comment by frederikbosch** [comment]
Aight, good ideas!

**Comment by sagikazarmark** [comment]
From my POV this is ready to be merged.

**Comment by waahhhh** [comment]
since June 2017 the symbol has changed. ₿
Source: https://en.bitcoin.it/wiki/Bitcoin_symbol
See: https://en.wiktionary.org/wiki/%E2%82%BF

**Comment by frederikbosch** [comment]
Could you create a PR?

**Pull request merged**
