### PR TITLE
Update README.md

### LINKED ISSUE #318: Remove integration section from README
Since this will be a new version, very likely to be incompatible with those (need to check), also we will have our own money bundle.

@frederikbosch WDYT?

### PR DESCRIPTION
**Pull request by frederikbosch**
Fixes #318 and adds some words on testing.

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Sorry, I am already doing this and a bit more which will conflict

**Comment by sagikazarmark** [comment]
Will integrate the test part

**Comment by frederikbosch** [comment]
Cool.

**Comment by frederikbosch** [comment]
Maybe add the logo in the README too. Now there is only one location where it is visible.

**Comment by sagikazarmark** [comment]
Good idea

**Pull request closed without merging**
