### PR TITLE
bitcoin support for formatter and parser

### LINKED ISSUE #97: Bitcoin not supported by stringToUnits()
Because stringToUnits() explicitly expects only 2 trailing decimals, it cannot support Bitcoin and we see "The value could not be parsed as money"

### PR DESCRIPTION
**Pull request by frederikbosch**
Fixes #97.

@thedavidmeister Would you please have a look at this PR? I have never done anything with bitcoins. Actually, I have no clue how to parse and/or formatter this currency. I just had a lookup what the currency code is and how a bitcoin symbol looks like. I would really appreciate your feedback. Of course, anyone else can give feedback too.

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Does Bitcoin support subunits?

**Comment by frederikbosch** [comment]
Some forum said it does, even up to 8 fractions at this moment

**Comment by sagikazarmark** [comment]
Ok, thanks

**Comment by frederikbosch** [comment]
@sagikazarmark https://millybitcoin.com/can-i-buy-a-fraction-of-a-bitcoin/ was my source.

**Comment by frederikbosch** [comment]
Regarding code style: I do know if I am happy with one constant in the formatter and one constant in the parser. Maybe there should be a separate object. What do you think @sagikazarmark?

**Comment by sagikazarmark** [comment]
I am fine with the constant

**Comment by frederikbosch** [comment]
This can perfectly wait for `3.1.0` or `3.0.1`.

**Comment by sagikazarmark** [comment]
In that case: can you resubmit the PR against master as soon as I renamed nextrelease to master?

**Comment by frederikbosch** [comment]
Sure, happy to do so. This was just a maintenance PR.

**Pull request closed without merging**
