### PR TITLE
Correct scale for add/subtract

### PR DESCRIPTION
**Pull request by angekouf**
In add and subtract functions you run bcmath with 0 scale which floored the result.

### CODE REVIEW

**Comment by sagikazarmark** [comment]
@frederikbosch can you please review this?

**Comment by frederikbosch** [comment]
@sagikazarmark Will do, it seems OK. But I am missing tests that prove the point.

@angekouf Can you add a test that shows that there the calculator is not correct at some point?

**Comment by sagikazarmark** [comment]
Ping @angekouf can you please take a look at the tests?

**Comment by sagikazarmark** [comment]
Ping @angekouf can you please take a look at the tests?

**Comment by frederikbosch** [comment]
Tests fail, no clear reason why to do it. It can only make sense when using PreciseMoney. Closing until better explanation given.

**Pull request closed without merging**
