### PR TITLE
Converter, convertAndReturnWithCurrencyPair and convertAgainstCurrencyPair methods

### LINKED ISSUE #498: Allow Converter to accept a CurrencyPair
As per the current documentation, you can get a conversion rate and convert a `Money` object to another currency as follows:

```php
$exchangeRate = $exchange->quote(new Currency('GBP'), new Currency('USD'));
$tenPoundsInDollars = $converter->convert(Money::GBP(1000), new Currency('USD'));
```

We need to log the exchange rate that was used for a conversion alongside the converted value. We can do the above, but that relies on `$exchange->quote()` returning the same value when called by `Converter::convert()`, which in some cases may not be true.

I suggest we add a method to `Converter` to allow a value and a `CurrencyPair` to be passed in, rather than having `Converter` always call `Exchange::quote()`:

```php
$exchangeRate = $exchange->quote(new Currency('GBP'), new Currency('USD'));
$tenPoundsInDollars = $converter->convertFromCurrencyPair(Money::GBP(1000), $exchangeRate);
```

### PR DESCRIPTION
**Pull request by frederikbosch**
Fixes #498, supersedes #502.

This PR provides:
1. `Converter#conversion` to get a combination of `Money` and the `CurrencyPair` that was used for conversion.
2. `Converter#convertAgainst`, to convert against a known `CurrencyPair`, and does make any call to an exchange

Why? When an amount is the result of a conversion, this amount usually saved together with the conversion rate. The method `Converter#conversion` helps to fulfill this need directly. While `Converter#convertAgainst` helps to convert an amount based on a saved `CurrencyPair`.

### CODE REVIEW

**Comment by frederikbosch** [comment]
@sagikazarmark @Ocramius This PR and probably a PR related to calculators will be the last PRs before tagging version 4.0 beta 1. Since @Ocramius contributed so much already, and therefore has specific knowledge of the upcoming release, I would kindly like to ask him if he is prepared to review this PR.

**Comment by Ocramius** [comment]
I read through it, but naming/API does not really makes much sense to me 🤔

**Comment by frederikbosch** [comment]
I agree. The names of the methods in the `Converter` class are too close. `convert` must stay for BC reasons, and I think that name fits the purpose. Maybe I should be more explicit for `convertAgainst` and change it into `convertAgainstCurrencyPair`. 

But then what to do with `conversion`? I tried to lookup if there is a name inside the *exchange domain* that fits this purpose but I was not able to find it. It's like you stand at the counter of the exchange office and you have just received money in the new currency *with* a receipt that shows you the currency pair. What do you say of `convertWithReceipt` and return `[Money, CurrencyPair]`?

**Comment by frederikbosch** [comment]
The PR was updated with improved method names.

**Pull request merged**
