### PR TITLE
fix gmp division of negative

### LINKED ISSUE #538: Divisions throws InvalidArgumentException "Invalid fractional part" when using GmpCalculator
```
$value = new Money('500', new Currency('USD'));
$p = $value->divide(110); //throws exception
```

### PR DESCRIPTION
**Pull request by frederikbosch**
Fixes #538

### CODE REVIEW

**Comment by frederikbosch** [comment]
@sagikazarmark When dividing the a negative amount the outcomes are different. The calculation `-500 / 110` results in `-4.54545454545455` according to PHP and GMP, whereas BC says it is `-4.54545454545454`. I think that BC Math is not rounding, but using the scale argument to determine the number of fractional digits.

**Comment by frederikbosch** [comment]
The solution could be.

1. Only add the negative division test to the GMP calculator.
2. Another fix.

**Comment by hellodave76** [comment]
> The solution could be.

Seeing as the problem doesn't originate inside moneyphp, maybe an acceptable solution would be to loosen the test condition, like trimming the values down to 12 decimal places?

**Comment by frederikbosch** [comment]
@hellodave76 Good suggestion, merged.

**Pull request merged**
