### PR TITLE
Update to new Travis location

### PR DESCRIPTION
**Pull request by frederikbosch**

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Good catch :+1:

**Comment by frederikbosch** [comment]
@sagikazarmark I dont have permission to close issues and write to the repos. Is that intentional?

**Comment by sagikazarmark** [comment]
No, it's not. :) Lemme fix that :D

**Comment by sagikazarmark** [comment]
You are now super-god-admin.

**Comment by frederikbosch** [comment]
Woah, that feels great! ;)

**Pull request merged**
