### PR TITLE
Fix Formatter trailing decimal point when subunit is 0

### PR DESCRIPTION
**Pull request by elazer**

### CODE REVIEW

**Comment by frederikbosch** [comment]
@elazer could you add tests for this?

**Comment by elazer** [comment]
There is a test for this already, but for some reason the tests passed even though it should have failed.

$this->assertEquals(1, '1.'); does not fail.

Any ideas why?

**Comment by frederikbosch** [comment]
@elazer assertEquals means ==, so I guess 1. is interpreted as a float which == 1 as an int. The test should be changed to assertSame, meaning ===. Then it will fail I guess. The end result should be assertSame('1', $formattedMoney).

**Comment by frederikbosch** [comment]
@sagikazarmark Why is this failing? Dont get the sphinx problem.

**Comment by frederikbosch** [comment]
@sagikazarmark Thanks for fixing!

**Comment by frederikbosch** [comment]
@elazer Thanks for the PR

**Pull request merged**
