### PR TITLE
Allow `psr/cache: ^1.0|^2.0|^3.0`

### PR DESCRIPTION
**Pull request by umpirsky**

### CODE REVIEW

**Comment by frederikbosch** [comment]
This is great. I don't see any reason not to merge this.

**Comment by frederikbosch** [comment]
Let's go for `^1.0.1 || ^2.0 || ^3.0`, then I'll merge.

**Comment by umpirsky** [comment]
Done.

**Comment by frederikbosch** [comment]
I will create a tag for this this week.

**Comment by frederikbosch** [comment]
Thanks for the work!

**Comment by umpirsky** [comment]
Thanks for merging that fast. :+1:

**Comment by umpirsky** [comment]
@frederikbosch Any updates on this?

**Pull request merged**
