### PR TITLE
Refactors ISOCurrencies, removes duplication of code.

### PR DESCRIPTION
**Pull request by Sharom**

### CODE REVIEW

**Comment by frederikbosch** [comment]
I dont have a problem with this. However, I do prefer isset over array_key_exists. But I dont have a specific reason why.

**Comment by sagikazarmark** [comment]
I will tell you the reason: the key differences are that isset is a language construct, array_key_exists is not, also the first checks if an array has a value for a specific key, while the latter checks if a specific key exists in the array (without accessing the value).

**Comment by frederikbosch** [comment]
Will be merged when Travis feels OK with #359.

**Comment by frederikbosch** [comment]
Thanks, merged and tagged.

**Pull request closed without merging**
