### PR TITLE
tests: mark test as skippable if locale is not available

### PR DESCRIPTION
**Pull request by Chris53897**
This tests fails for me locally, because i do not have the locale installed.
I have to run tests one by one instead of `composer test`
With this change it makes it easier to test local.

### CODE REVIEW

**Comment by frederikbosch** [comment]
But, if in CI, the test must fail if the locale is not there. So this solution is a little to easy.

**Comment by Chris53897** [comment]
ok, i will think about a more robust solution.

**Comment by Chris53897** [comment]
Is it valid to change it to a more commonly used Locale?
I guess US is comma seperated and the sense of the test ist still correct.
Please check this.

**Comment by frederikbosch** [comment]
I rather leave it as is.

**Pull request closed without merging**
