### PR TITLE
Add a comparator for use in PHPUnit tests

### PR DESCRIPTION
**Pull request by willemstuursma**
Adds a comparator for use in PHPUnit so you can use assertEquals() on Money objects.

### CODE REVIEW

**Comment by frederikbosch** [comment]
@willemstuursma Never knew this PHPUnit function. Looks good. Could you also add one test to use this comparator? I would like to see what a new test would look like. And we could rewrite tests to this methodology. My final question would be if there is support for this in the latest PHPUnit (still 6?).

**Comment by willemstuursma** [comment]
What's up with the overzealous StyleCI job @frederikbosch?

**Comment by frederikbosch** [comment]
@willemstuursma Dunno, I believe that @sagikazarmark is already looking at it. Others were also complaining.

**Comment by frederikbosch** [comment]
@willemstuursma I see you added a test to the comparator. That is perfect, but not what I meant. I'd like to see a test that is using it within the current test framework, e.g. [here](https://github.com/moneyphp/money/blob/master/tests/MoneyTest.php#L22). You told me that you will have to add it to the PHPUnit bootstrap or to the XML file. I prefer the XML file since we already have that one. Finally I think this should live within an own namespace. Since it is PHPUnit specific, I would suggest something like `Money\PhpUnit\Comparator`.

So, in order to merge.
- [ ] add a test to the current framework, using the XML file if possible
- [ ] move to namespace

**Comment by frederikbosch** [comment]
@willemstuursma Looks good. Question, why is the `Comparator` class itself not final? Is there a reason for it?

**Comment by willemstuursma** [comment]
Thanks @frederikbosch. Not used to `final` classes, added.

**Comment by frederikbosch** [comment]
@sagikazarmark In my opinion this can be merged in. This could - over time - give a huge cleanup to our unit tests.

**Comment by frederikbosch** [comment]
Without any complaints, this will be merged Thursday.

**Comment by frederikbosch** [comment]
Wonderful, thank you!

**Pull request merged**
