### PR TITLE
PHPStorm suggests to require ext-json

### PR DESCRIPTION
**Pull request by gmponos**

### CODE REVIEW

**Comment by frederikbosch** [comment]
Can you add it to suggest? It is not required.

**Comment by gmponos** [comment]
You have Currency and Money object implement `JsonSerializable`.

http://php.net/manual/en/class.jsonserializable.php

Now that I've checked it online I see that PHP says that json extension is compiled into PHP by default

see http://php.net/manual/en/json.installation.php

🤔 so why does PHPStorm suggests this? Is it possible for someone to compile PHP without this extensions?

**Comment by browner12** [comment]
correct, while 99% of PHP installs are going to have the JSON extension compiled in by default, it is possible to omit it.

I would agree that this belongs in 'require' since a package class is implementing `JsonSerializable`.

**Comment by sagikazarmark** [comment]
Yeah, it looks like it's technically required.

**Comment by gmponos** [comment]
it just occurred to me... https://twitter.com/gmponos/status/1073611157792006144

**Pull request merged**
