### PR TITLE
Added static constructor for converting numerics into money objects

### PR DESCRIPTION
**Pull request by pinkbigmacmedia**
Added static constructor for converting numeric values into money objects.

### CODE REVIEW

**Comment by frederikbosch** [comment]
@pinkbigmacmedia Why not using a parser for this? I think the `StringToUnitsParser` will help you converting a decimal.

```php
$parser = new StringToUnitsParser();
$money = $parser->parse((string) 999.99, 'EUR');
```

**Comment by pinkbigmacmedia** [comment]
@frederikbosch Fair enough. I just found the one-liner as one way for creating money objects kind of handy.

Could we potentially have something like this on `Money\Money`:
```php
/**
  *
  * @param  string  $money
  * @param  string  $currency
  * @return Money
  */
public static function fromString($money, $currency)
{
    $parser = new StringToUnitsParser();
    return $parser->parse( (string) $money, $currency);
}
```

**Comment by sagikazarmark** [comment]
I am :-1: on this. Although it might be handy, Money should preserve it's identity as a value object and should not be polluted with all the possible instantiation stuff. The reason why we implemented parsers is to allow devs creating money objects whatever way they want.

**Comment by frederikbosch** [comment]
I have nothing to add to that.

**Pull request closed without merging**
