### PR TITLE
Fix specs

### PR DESCRIPTION
**Pull request by bendavies**
The specs i've fixed weren't asserting the results

### CODE REVIEW

**Comment by frederikbosch** [comment]
Why do need `beberlei/assert` to [check if something is true](https://github.com/beberlei/assert/blob/master/lib/Assert/Assertion.php#L1316)?

**Comment by sagikazarmark** [comment]
We don't. I got the point, I will fix these tests and close this PR.

**Comment by bendavies** [comment]
@frederikbosch because the specs weren't asserting/checking anything at all

**Comment by sagikazarmark** [comment]
No need for assertion: `->shouldReturn(something);`

**Comment by bendavies** [comment]
@sagikazarmark not possible without refactoring as the return from `equal` isn't a prophecy, it's a real `Money` object

**Comment by bendavies** [comment]
@sagikazarmark are you going to fix this yourself?

**Comment by frederikbosch** [comment]
Fixed in PR #260.

**Pull request closed without merging**
