### PR TITLE
Full PHP 8.1 support

### PR DESCRIPTION
**Pull request by driesvints**
~Blocked by https://github.com/phpspec/phpspec/pull/1397 a new tag on PhpSpec.~

### CODE REVIEW

**Comment by driesvints** [comment]
@frederikbosch can you maybe approve the workflows here so the builds can run and I can look into more fixes that are needed for PHP 8.1?

**Comment by frederikbosch** [comment]
Early support for PHP 8.1 via new release 4.0.3. Please tag me as soon as PHPspec blocking PR is merged. Then I will try to provide full support by helping getting this PR out of the door.

**Comment by driesvints** [comment]
My PR got closed but https://github.com/phpspec/phpspec/pull/1407 was merged. Waiting for it to be tagged.

**Comment by frederikbosch** [comment]
Cool, please let me know when we can proceed here.

**Comment by frederikbosch** [comment]
Why isn't the workflow running for your c169254 commit?

**Comment by driesvints** [comment]
@frederikbosch unsure because they seem to be running on my fork: https://github.com/driesvints/money/actions

Phpbench seems to still be failing here: https://github.com/driesvints/money/runs/5535118972?check_suite_focus=true#step:7:223

**Comment by driesvints** [comment]
I bumped both Phpbench and PhpSpec. But now I'm getting quite a lot of Psalm errors because I needed to bump Psalm to the latest version. 

@frederikbosch I'd appreciate any help with solving these.

**Comment by frederikbosch** [comment]
@driesvints I saw what you were doing- have been pushing the approve button the whole time. Great work for now already. I'll try to have a look at these psalm errors this week.

**Comment by driesvints** [comment]
Thanks @frederikbosch!

**Comment by frederikbosch** [comment]
Merci beaucoup @driesvints!

**Comment by driesvints** [comment]
Awesome, thanks @frederikbosch!

**Pull request merged**
