### PR TITLE
Update checks.ymlm

### PR DESCRIPTION
**Pull request by Tunechi2323**

### CODE REVIEW

**Comment by frederikbosch** [comment]
What's the function of `check` here?

**Comment by Tunechi2323** [comment]
> What's the function of `check` here?

I'm sorry come again

**Comment by frederikbosch** [comment]
You have created a PR that adds the word `check` inside `checks.yml`. Why do we need that?

**Comment by Tunechi2323** [comment]
My phone was messing up so I had to use my tablet I actually didn't know that

**Comment by Ocramius** [comment]
@frederikbosch this account was created 4h ago and is already spamming everywhere: reporting it.

**Comment by frederikbosch** [comment]
After those two stupid replies, I reported it immediately. Long live AI...

**Pull request closed without merging**
